#!/usr/bin/env python3
"""
05_run_metal.py — Generate METAL command script and run meta-analysis.

IVW fixed-effects meta-analysis with:
  - Per-study genomic control correction
  - Heterogeneity statistics (Cochran's Q, I²)
  - Allele-aware alignment

Output:
  {outdir}/metal_script.txt        — METAL command file
  {outdir}/meta_result_1.tbl       — Raw METAL output
  {outdir}/metal.log               — METAL stdout
"""

import argparse
import glob
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(__file__))
from utils.logging_utils import (
    setup_logging, log_info, log_warn, log_error,
    log_step, log_substep, log_separator,
    log_timer_start, log_timer_end,
)


def load_params(params_file: str) -> dict:
    params: dict = {"ds_names": []}
    with open(params_file) as f:
        for line in f:
            line = line.strip()
            if line.startswith("key") or not line:
                continue
            parts = line.split("\t", 1)
            key = parts[0]
            val = parts[1] if len(parts) > 1 else ""
            if key == "ds_name":
                params["ds_names"].append(val)
            else:
                params[key] = val
    return params


def main():
    parser = argparse.ArgumentParser(description="Run METAL meta-analysis")
    parser.add_argument("--params", required=True)
    parser.add_argument("--gwas-dir", required=True, help="Dir containing {ds}_merged.tsv files")
    parser.add_argument("--outdir", required=True)
    args = parser.parse_args()

    setup_logging()
    os.makedirs(args.outdir, exist_ok=True)

    params = load_params(args.params)
    case_label = params.get("case_label", "unknown")
    min_datasets = int(params.get("min_datasets", 2))

    log_step(f"Meta-analysis: {case_label}")

    # Find available merged result files
    input_files = []
    for ds in params["ds_names"]:
        merged = os.path.join(args.gwas_dir, f"{ds}_merged.tsv")
        if os.path.exists(merged):
            # Verify it has content
            with open(merged) as f:
                header = f.readline()
                first_data = f.readline()
            if first_data.strip():
                input_files.append((ds, merged))
                log_info(f"  Input: {ds} → {merged}")
            else:
                log_warn(f"  {ds}: merged file is empty — skipping")
        else:
            log_warn(f"  {ds}: no merged results found — skipping")

    n_inputs = len(input_files)
    log_info(f"Input datasets: {n_inputs}")

    if n_inputs < min_datasets:
        log_error(f"Need at least {min_datasets} datasets, found {n_inputs}")
        sys.exit(1)

    # Generate METAL script
    metal_script_path = os.path.join(args.outdir, "metal_script.txt")
    metal_out_prefix = os.path.join(args.outdir, "meta_result_")

    lines = [
        f"# METAL script for {case_label}",
        f"# IVW fixed-effects meta-analysis across {n_inputs} datasets",
        f"# Generated by 05_run_metal.py",
        "",
        "# Use inverse-variance weighted (STDERR) scheme",
        "SCHEME   STDERR",
        "SEPARATOR TAB",
        "",
        "# Column name mappings",
        "MARKER   SNP",
        "ALLELE   A1 A2",
        "EFFECT   BETA",
        "STDERR   SE",
        "PVALUE   P",
        "WEIGHT   N",
        "",
        "# Apply genomic control correction per study",
        "# Corrects for residual population stratification",
        "GENOMICCONTROL ON",
        "",
        "# Track allele frequencies if available",
        "AVERAGEFREQ ON",
        "MINMAXFREQ ON",
        "FREQLABEL A1_FREQ",
        "",
        "# Enable heterogeneity analysis (Cochran's Q, I²)",
        "HETEROGENEITY ON",
        "",
    ]

    for ds, filepath in input_files:
        lines.extend([
            f"# --- {ds} ---",
            f"PROCESS {filepath}",
            "",
        ])

    lines.extend([
        "# --- Execute ---",
        f"OUTFILE {metal_out_prefix} .tbl",
        "ANALYZE HETEROGENEITY",
        "",
        "QUIT",
    ])

    with open(metal_script_path, "w") as f:
        f.write("\n".join(lines))
    log_info(f"METAL script: {metal_script_path}")

    # Run METAL
    log_substep("Running METAL")
    log_timer_start("METAL execution")

    metal_log_path = os.path.join(args.outdir, "metal.log")

    try:
        result = subprocess.run(
            ["metal", metal_script_path],
            capture_output=True,
            text=True,
            timeout=7200,  # 2 hour timeout
        )

        # Write METAL stdout/stderr to log
        with open(metal_log_path, "w") as f:
            f.write("=== METAL STDOUT ===\n")
            f.write(result.stdout)
            f.write("\n=== METAL STDERR ===\n")
            f.write(result.stderr)

        # Log key lines from METAL output
        for line in result.stdout.split("\n"):
            line = line.strip()
            if not line:
                continue
            # Log important METAL messages
            if any(kw in line.lower() for kw in [
                "genomic control", "lambda", "processing",
                "markers", "completed", "error", "warning",
                "## Executing", "## Meta-analysis"
            ]):
                log_info(f"  METAL: {line}")

        if result.returncode != 0:
            log_error(f"METAL exited with code {result.returncode}")
            log_error(f"METAL stderr: {result.stderr[:1000]}")
            sys.exit(1)

    except subprocess.TimeoutExpired:
        log_error("METAL timed out after 2 hours")
        sys.exit(1)
    except FileNotFoundError:
        log_error("METAL executable not found in PATH")
        sys.exit(1)

    log_timer_end("METAL execution")

    # Check output
    result_file = f"{metal_out_prefix}1.tbl"
    if not os.path.exists(result_file):
        log_error(f"METAL output not found: {result_file}")
        log_error("Check metal.log for details")
        sys.exit(1)

    # Count variants
    with open(result_file) as f:
        n_variants = sum(1 for _ in f) - 1

    log_info(f"Meta-analysis result: {result_file}")
    log_info(f"  Variants: {n_variants}")

    # Quick preview of top hits
    log_substep("Top 10 hits by p-value")
    import pandas as pd
    df = pd.read_csv(result_file, sep="\t", nrows=1000000)
    p_col = [c for c in df.columns if "p-value" in c.lower() or c == "P-value"][0]
    top = df.nsmallest(10, p_col)
    for _, row in top.iterrows():
        marker = row.get("MarkerName", "?")
        pval = row.get(p_col, "?")
        effect = row.get("Effect", "?")
        direction = row.get("Direction", "?")
        log_info(f"  {marker}  P={pval:.2e}  BETA={effect:.4f}  Dir={direction}")

    log_separator()
    log_info("Meta-analysis complete")
    log_info(f"Full METAL log: {metal_log_path}")


if __name__ == "__main__":
    main()
